// Generated by gencpp from file project_weather_x/Weather.msg
// DO NOT EDIT!


#ifndef PROJECT_WEATHER_X_MESSAGE_WEATHER_H
#define PROJECT_WEATHER_X_MESSAGE_WEATHER_H

#include <ros/service_traits.h>


#include <project_weather_x/WeatherRequest.h>
#include <project_weather_x/WeatherResponse.h>


namespace project_weather_x
{

struct Weather
{

typedef WeatherRequest Request;
typedef WeatherResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Weather
} // namespace project_weather_x


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project_weather_x::Weather > {
  static const char* value()
  {
    return "bacc311a1463e9aad37df67c2ecee977";
  }

  static const char* value(const ::project_weather_x::Weather&) { return value(); }
};

template<>
struct DataType< ::project_weather_x::Weather > {
  static const char* value()
  {
    return "project_weather_x/Weather";
  }

  static const char* value(const ::project_weather_x::Weather&) { return value(); }
};


// service_traits::MD5Sum< ::project_weather_x::WeatherRequest> should match 
// service_traits::MD5Sum< ::project_weather_x::Weather > 
template<>
struct MD5Sum< ::project_weather_x::WeatherRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project_weather_x::Weather >::value();
  }
  static const char* value(const ::project_weather_x::WeatherRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_weather_x::WeatherRequest> should match 
// service_traits::DataType< ::project_weather_x::Weather > 
template<>
struct DataType< ::project_weather_x::WeatherRequest>
{
  static const char* value()
  {
    return DataType< ::project_weather_x::Weather >::value();
  }
  static const char* value(const ::project_weather_x::WeatherRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project_weather_x::WeatherResponse> should match 
// service_traits::MD5Sum< ::project_weather_x::Weather > 
template<>
struct MD5Sum< ::project_weather_x::WeatherResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project_weather_x::Weather >::value();
  }
  static const char* value(const ::project_weather_x::WeatherResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project_weather_x::WeatherResponse> should match 
// service_traits::DataType< ::project_weather_x::Weather > 
template<>
struct DataType< ::project_weather_x::WeatherResponse>
{
  static const char* value()
  {
    return DataType< ::project_weather_x::Weather >::value();
  }
  static const char* value(const ::project_weather_x::WeatherResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_WEATHER_X_MESSAGE_WEATHER_H
